
version: 2.1

jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Start job:"
          command: "start logs:"

  print_hello: 
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "print_hello"
          command: "echo Hello"

  print_world: 
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "print_world"
          command: "echo world!"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  hello-workflow:
    jobs:
      - say-hello
      - print_hello:
          filters:
            branches:
              only: main
      - print_world: 
          requires:
            - print_hello
